### ISSUE TITLE
`ERROR: No IDs are mapped` when Ensembl gene ids are provided as inputs

### ISSUE THREAD

**Issue by integratebio** [bzhanglab/WebGestaltR#14]
Hello, 
I am using the `WebGestaltR`s 0.4.4 version on R 4.1.2.
I got the `ERROR: No IDs are mapped` error when I provided Ensembl gene ids using `interestGeneType="ensembl_gene_id"` and `referenceGeneType="ensembl_gene_id"` arguments to the example code from the vignette i.e.
```
geneFile <- system.file("extdata", "interestingGenes.txt", package="WebGestaltR")
refFile <- system.file("extdata", "referenceGenes.txt", package="WebGestaltR")
outputDirectory <- getwd()
enrichResult <- WebGestaltR(enrichMethod="ORA", organism="hsapiens",
enrichDatabase="pathway_KEGG", interestGeneFile=geneFile,
interestGeneType="ensembl_gene_id", referenceGeneFile=refFile,
referenceGeneType="ensembl_gene_id", isOutput=TRUE,
outputDirectory=outputDirectory, projectName=NULL)
```
The full error message was as follows:
```
Loading the functional categories...
Loading the ID list...                                                                                             
ERROR: No IDs are mapped. Please check your input.Error in idMappingGene(organism = organism, dataType = dataType, inputGeneFile = inputGeneFile,  : 
  ERROR: No IDs are mapped. Please check your input.
```

For your reference, here are the input files I used: [interestingGenes.txt](https://github.com/bzhanglab/WebGestaltR/files/8791891/interestingGenes.txt) [referenceGenes.txt](https://github.com/bzhanglab/WebGestaltR/files/8791890/referenceGenes.txt) (protein coding genes)
They are indeed Ensembl IDs. So I am not sure why I am getting this error.

Could you please let me know you advice on how I should be providing the Ensembl gene ids as input?

PS: I should note that interestingly, if I provide the same inputs i.e. Ensembl IDs with `interestGeneType="genesymbol"` and `referenceGeneType="genesymbol"` arguments, I don't get the error. But I am not sure if should trust the outputs of the enrichment analysis I got by this way. I would like if I could explicitly "tell" `WebGestaltR` that I am providing Ensembl IDs. I hope there is a way to do that.

**Comment by yxngl** [comment]
Hi, geneFile <- system.file("extdata", "interestingGenes.txt",
package="WebGestaltR") get example data from the package. The files are in
gene symbols. You should just use the file path to your input files.
