### ISSUE TITLE
WebGestaltR error associated with user provided .gmt file

### ISSUE THREAD

**Issue by nhu119** [bzhanglab/WebGestaltR#16]
Thank you for developing and maintaining WebGestalt. I have been using the R package to perform Over-Representation Analysis and would like to use the latest GO gene sets from MSigDB (v7.5.1; http://www.gsea-msigdb.org/gsea/msigdb/download_file.jsp?filePath=/msigdb/release/7.5.1/c5.go.v7.5.1.symbols.gmt). I used the function "readGmt" to lead the .gmt file into my R environment, and then I tried running the WebGestaltR function using the following command 

WebGestaltR(enrichMethod="ORA",
                            organism="hsapiens",
                            enrichDatabaseFile = Go,
                            enrichDatabaseType = "genesymbol",
                            interestGene=sig_genes,
                            interestGeneType="genesymbol",
                            referenceSet="genome_protein-coding",
                            referenceGeneType="genesymbol",
                            minNum=5,
                            sigMethod="top",
                            topThr=20,
                            isOutput=TRUE,
                            outputDirectory=outputDirectory,
                            projectName=outName)

When I run it, I get the following error: 

"Error in startsWith(gmtFile, "http://") : non-character object(s)" 

I double checked my .gmt fie, and all columns are characters. Can you please offer some insight as to why I am getting this error? As an aside, I have been able to successfully run WebGestaltR using the gene set files readily available with the package using "enrichDatabase". Thank you so much for your time, help, and insight.

**Comment by yxngl** [comment]
Sorry. I have been busy with a manuscript recently and just replied in the
Google Forum.
