### ISSUE TITLE
Error with WebgestaltR

### ISSUE THREAD

**Issue by bryanrhelm** [bzhanglab/WebGestaltR#17]
Hello,
I am doing functional enrichment with some up- and downregulated gene lists, and I'm getting an error when I try to use the community contributed hallmarks of cancer database. Here is my code:

c0vs1.up.hallmarks <- WebGestaltR(enrichMethod = "ORA",
                             organism = "mmusculus",
                             enrichDatabase = "community-contributed_Hallmark50",
                             interestGene = rownames(degs.0vs1.up),
                             interestGeneType = "genesymbol",
                             referenceSet = "genome",
                             isOutput = F,
                            minNum = 5)

This error is produced when I run the code:
"Loading the functional categories...
ERROR: Please select the functional database or select 'others' to upload the functional database.Error in loadGeneSet(organism = organism, enrichDatabase = enrichDatabase,  : 
ERROR: Please select the functional database or select 'others' to upload the functional database."

* I can get an output if I change the organism to "hsapiens" and convert the mouse gene symbols to human by converting to uppercase. 

I was wondering if there is a way to use the mouse gene symbols directly to perform functional enrichment for the MsigDB Hallmarks database or is it appropriate to convert to human symbols for the enrichment?

**Comment by yxngl** [comment]
Hi, MsigDB Hallmarks is just for human. You could potentially map your
genes to human orthologs and use it. But whether it is appropriate is up
to you. I would just do pathway enrichment first in mouse and it shouldn't
miss out too much. But it could be a supplementary result as well.
