### ISSUE TITLE
IdMapping() default host

### ISSUE THREAD

**Issue by westbrooktm** [bzhanglab/WebGestaltR#19]
Since commit 6fb1b17 on Feb 9, 2023, the IdMapping() function's default host of "http://www.webgestalt.org/" no longer works and gives an "Organism is missing." error message, as the proper link was updated to "https://www.webgestalt.org/". Specifying the host with the "s" fixes the issue, but it would be nice for the default and the listArchiveUrl() function to reflect the change.

**Comment by iblacksand** [comment]
This is updated on the Github, and will be reflected on the package soon. Thanks for the report.
