### ISSUE TITLE
idMappingGene error

### ISSUE THREAD

**Issue by shengqh** [bzhanglab/WebGestaltR#21]
The code we ran successfully a few days ago now didn't work. We used hsapiens as organism name. Also, we are still using the 0.4.4 version. I am wondering if that is caused by the change from http to https url. 

Loading the ID list...
Organism is missing.
Error in idMappingGene(organism = organism, dataType = dataType, inputGeneFile = inputGeneFile,  :
  Organism is missing.
Calls: WebGestaltR ... .uploadGeneExistingOrganism -> idMapping -> idMappingGene

**Comment by iblacksand** [comment]
You are correct that it is dealing with that change from http to https. To fix this in version 0.4.4 you can manually specify `hostName` in function calls with the updated url. 

For example
```R
idMapping(organism=organism, ..., hostName="https://www.webgestalt.org"))
```

This is fixed in 0.4.5 which should be available soon. Let me know if you have questions.

**Comment by shengqh** [comment]
I upgraded to v0.4.5 and it worked. However, if you can update the server side to provide more accurate error message for those who is still using old version, that would be very helpful.

**Comment by iblacksand** [comment]
For the time being, the HTTP api was restored, so manually setting `hostName` on older versions isn't required.
