### ISSUE TITLE
One or two sided P value for ORA?

### ISSUE THREAD

**Issue by Nana-Liu-genetics** [bzhanglab/WebGestaltR#24]
The P values for ORA are calculated by the code:
pValue=1-phyper(.data$overlap - 1, length(interestGene), length(referenceGene) - length(interestGene), .data$size, lower.tail=TRUE, log.p=FALSE)
I want to confirm that the P values for ORA are one-sided.
Looking forward to your reply.

**Comment by yxngl** [comment]
It is one-sided.
