### ISSUE TITLE
appropriate background expression ‘universes’ for GSEA

### ISSUE THREAD

**Issue by Pchaskar** [bzhanglab/WebGestaltR#28]
I would like to use the GSEA approach on the pre-ranked proteomics data (~ 2000 proteins). I would like to know if I can provide a reference list (appropriate background expression ‘universes’) to the GSEA to estimate the enrichment better.  Reference option available in ORA but not GSEA.
Thanks

**Comment by yxngl** [comment]
Hi, that is not possible. For GSEA, you can think the reference is the
input space itself.
