### ISSUE TITLE
Warning when loading reference gene list

### ISSUE THREAD

**Issue by Pweidemueller** [bzhanglab/WebGestaltR#3]
Dear zhanglab,
I get following warning when doing an Overrepresentation analysis with a gene list and a custom reference gene list. using WebGestaltR. When the reference list is loaded, following warning flashes: 

> Loading the functional categories...
> Loading the ID list...
> Loading the reference list...
> data length [43707] is not a sub-multiple or multiple of the number of rows [10929]

I can't make sense of that warning, because when I ran the exact same analysis before I did not get it. Can I just ignore it? I still get enrichment results, but when I run the analysis online on your web applet 1. no warning flashes and 2. the results differ from the ones returned by WebGestaltR. So I'm unsure if I can trust the analysis right now.

I attach the gene list and reference gene list. THis is the code I used:

`WebGestaltR(interestGeneFile= allSpecies_CorrelatingGenes_Testis.txt,
            interestGeneType="ensembl_gene_id",
            enrichMethod="ORA",
            organism="hsapiens",
            enrichDatabase="geneontology_Biological_Process_noRedundant",
            referenceGeneFile=allSpecies_ReferenceGenes_Testis.txt,
            referenceGeneType="ensembl_gene_id",
            fdrMethod="BH", # Benjamini Hochberg
            sigMethod="fdr",
            fdrThr=0.01,
            isOutput=TRUE,outputDirectory="Extract_PeakGenes/Biological_Process", projectName=allSpecies)`

I appreciate any help!
[allSpecies_ReferenceGenes_Testis.txt](https://github.com/bzhanglab/WebGestaltR/files/3580012/allSpecies_ReferenceGenes_Testis.txt)
[allSpecies_CorrelatingGenes_Testis.txt](https://github.com/bzhanglab/WebGestaltR/files/3580013/allSpecies_CorrelatingGenes_Testis.txt)

**Comment by yxngl** [comment]
I tried with the latest version and it seems fine. Could you try to update to the latest version from CRAN?
