### ISSUE TITLE
WebGestalt web server is out of work

### ISSUE THREAD

**Issue by mglgc** [bzhanglab/WebGestaltR#30]
Hi,
The WebGestalt web server https://www.webgestalt.org/ is out of work. Just testing the GSEA sample run, the result is an error page:
"R error (1688396552)."
Thank you very much in advance for your reply.

**Comment by iblacksand** [comment]
The server should be back up now. Please try again and let us know if it isn't working.

**Comment by mglgc** [comment]
It's OK. Thank you very much for your promptly reply.
