### ISSUE TITLE
Error in WebGestaltRBatch for GSEA

### ISSUE THREAD

**Issue by danielnewhouse** [bzhanglab/WebGestaltR#4]
Hello, I am looking to use WebGestaltRBatch to process several .rnk files for GSEA. I can successfully run each .rnk file individually, but get the below error message when trying to run the .rnk files in batch.

In looking at the R code in GitHub, it seems that formatCheck is setting dataType=list when it should be dataType=rnk. The "test" folder only contains .rnk files.

Is there a workaround to this issue? I am not sure why the Batch mode analysis is not recognizing the .rnk files.

Thank you,
Daniel Newhouse

Error Message:
```{r}
Process file: ~test/MM.bisque4.rnk
Loading the functional categories...
Loading the ID list...
Error in formatCheck(dataType = dataType, inputGeneFile = inputGeneFile,  : 
  ERROR: For the user ID list, please upload a 'txt' file with only one column.
```

Code used that produced the error:
```{r}
WebGestaltRBatch(enrichMethod = "GSEA",
                 interestGeneFolder = "~/test", 
                 organism="hsapiens",
                 interestGeneType="genesymbol",
                 isParallel = FALSE, nThreads = 4, 
                 enrichDatabase = "geneontology_Biological_Process_noRedundant",
                 minNum=5, sigmethod="fdr", fdrMethod="BH")
```
Running this formatCheck code also reproduces the error:
```{r}
formatCheck(dataType = "list", inputGeneFile = "MM.bisque4.rnk")
```

However, if I change dataType to rnk, the error goes away
```{r}
formatCheck(dataType = "rnk", inputGeneFile = "MM.bisque4.rnk")
```

**Comment by yxngl** [comment]
Thanks. I will release a version on CRAN soon.
